### ISSUE TITLE
FCW C Server crash - send_packet_unit_short_info / json_dumps

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#165]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __find_specmb (format=0x7fea3db84c9f "%lld") at printf-parse.h:108
108     printf-parse.h: No such file or directory.
[Current thread is 1 (Thread 0x7fea3e9f6800 (LWP 32099))]
(gdb) bt full
#0  __find_specmb (format=0x7fea3db84c9f "%lld") at printf-parse.h:108
No locals.
#1  _IO_vfprintf_internal (s=s@entry=0x7ffebf51f580, format=format@entry=0x7fea3db84c9f "%lld", ap=ap@entry=0x7ffebf51f700) at vfprintf.c:1320
        thousands_sep = 0x0
        grouping = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
        done = 0
        f = <optimized out>
        lead_str_end = <optimized out>
        end_of_spec = <optimized out>
        work_buffer = "\000\000\000\000\000\000\000\000P)sdwU\000\000\f\000\000\000\000\000\000\000\001", '\000' <repeats 11 times>, "\352\177\000\000\000\000\000\000\000\000\000\000P\362Q\277\376\177\000\000 L\270=\352\177\000\000\210L\270=\352\177\000\000\000\000\000\000\000\000\000\000h\r\000\000\000\000\000\000\211L\270=\352\177\000\000\207L\270=\352\177\000\000h\000\000\000\000\000\000\000\002", '\000' <repeats 11 times>, "\376\177\000\000\242L\270=\352\177\000\000\000\000\000\000\352\177\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\000\000\000\000\001\000\000\000\n\000\000\000\000\000\000\000\367\366Q\277\376\177\000\000\000\000\000\000\376\177\000\000\000\000\000\000\000\000\000\000"...
        workstart = 0x0
        workend = <optimized out>
        ap_save = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7ffebf51f7e0, reg_save_area = 0x7ffebf51f720}}
        nspecs_done = 0
        save_errno = <optimized out>
        readonly_format = 0
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
        __result = <optimized out>
#2  0x00007fea3cdc6ff9 in ___vsnprintf_chk (s=0x7ffebf51f850 "", maxlen=<optimized out>, flags=1, slen=<optimized out>, format=0x7fea3db84c9f "%lld", args=args@entry=0x7ffebf51f700)
    at vsnprintf_chk.c:63
        sf = {f = {_sbf = {_f = {_flags = -72515583, _IO_read_ptr = 0x7ffebf51f850 "", _IO_read_end = 0x7ffebf51f850 "", _IO_read_base = 0x7ffebf51f850 "",
                _IO_write_base = 0x7ffebf51f850 "", _IO_write_ptr = 0x7ffebf51f850 "", _IO_write_end = 0x7ffebf51f8b3 "=\352\177", _IO_buf_base = 0x7ffebf51f850 "",
                _IO_buf_end = 0x7ffebf51f8b3 "=\352\177", _IO_save_base = 0x0, _IO_backup_base = 0x0, _IO_save_end = 0x0, _markers = 0x0, _chain = 0x0, _fileno = 1035488392,
                _flags2 = 132, _old_offset = 0, _cur_column = 0, _vtable_offset = 0 '\000', _shortbuf = "", _lock = 0x0, _offset = 3472895661634505863, _codecvt = 0x2f2472a8de8bf900,
                _wide_data = 0xffffffffffffffff, _freeres_list = 0x0, _freeres_buf = 0x3035393233373436, __pad5 = 3396966088557984000, _mode = -1,
                _unused2 = "\376\177\000\000\200\366Q\277\376\177\000\000p\371Q\277\376\177\000"}, vtable = 0x7fea3d07cfa0 <_IO_strn_jumps>}, _s = {_allocate_buffer_unused = 0x0,
              _free_buffer_unused = 0x1}},
          overflow_buf = "\022\000\000\000\000\000\000\000\371o\334<\352\177\000\000\001\200\255\373\376\177\000\000p\371Q\277\376\177\000\000p\371Q\277\376\177\000\000p\371Q\277\376\177\000\000p\371Q\277\376\177\000\000~\371Q\277\376\177\000"}
        ret = <optimized out>
#3  0x00007fea3cdc6f25 in ___snprintf_chk (s=<optimized out>, maxlen=<optimized out>, flags=<optimized out>, slen=<optimized out>, format=<optimized out>) at snprintf_chk.c:34
        arg = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7ffebf51f7e0, reg_save_area = 0x7ffebf51f720}}
        done = <optimized out>
#4  0x00007fea3db7d4ed in ?? () from /usr/lib/x86_64-linux-gnu/libjansson.so.4
No symbol table info available.
#5  0x00007fea3db7d670 in ?? () from /usr/lib/x86_64-linux-gnu/libjansson.so.4
No symbol table info available.
#6  0x00007fea3db7db3c in json_dump_callback () from /usr/lib/x86_64-linux-gnu/libjansson.so.4
No symbol table info available.
#7  0x00007fea3db7dbc4 in json_dumps () from /usr/lib/x86_64-linux-gnu/libjansson.so.4
No symbol table info available.
#8  0x00005577621bbec0 in send_packet_unit_short_info_100 ()
No symbol table info available.
#9  0x0000557761ff9b2f in send_unit_info ()

**Comment by andreasrosdal** [comment]
@cazfi
